version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: nuget
    directory: /src/GastroLeinefeldeAPI
    schedule: { interval: weekly }
  - package-ecosystem: nuget
    directory: /src/GastroLeinefeldeAPI.Tests
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /src/GastroLeinefeldeAPI
    schedule: { interval: weekly }
