all:
  hosts:
    gastro-prod:
      ansible_host: 157.180.95.55
      ansible_user: deploy        # или другой пользователь с sudo
      ansible_ssh_private_key_file: ~/.ssh/id_rsa   # путь к вашему приватному ключу