name: Infrastructure Apply

on:
  push:
    branches: [main]
    paths: ['terraform/**']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: opentofu-production
  cancel-in-progress: false

jobs:
  opentofu-apply:
    runs-on: ubuntu-latest
    environment:
      name: production   # требует ручного approval в GitHub Environments

    defaults:
      run:
        working-directory: terraform/live/production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: '1.12.1'

      - name: Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OBJ_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OBJ_SECRET_KEY }}
        run: tofu init -backend-config="endpoint=${{ secrets.OBJ_ENDPOINT }}"

      - name: Validate
        run: tofu validate

      - name: Apply
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_ssh_key_ids: ${{ secrets.SSH_KEY_IDS }}
        run: tofu apply -auto-approve